# -*- coding: utf-8 -*-
"""
Emit shop/assets/js/photos.js from the verified manifest.

Kept separate from data.js (which tools/build.py generates) so the catalogue and
the photography can each be regenerated without disturbing the other.

Products without their own photograph yet fall back to their aisle photograph —
a real picture of that department — so no tile ever shows a drawing.
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")

def main():
    with open(os.path.join(HERE, "photos.json"), encoding="utf-8") as f:
        man = json.load(f)["photos"]

    products, aisles, scenes, credits = {}, {}, {}, []
    for key, e in sorted(man.items()):
        kind = e.get("kind", "product")
        if kind == "product":
            products[key] = e["url"]
        elif kind == "aisle":
            aisles[key[len("aisle-"):]] = e["url"]
        else:
            scenes[key] = e["url"]
        credits.append({"k": key, "by": e["photographer"],
                        "at": e["profile"], "src": e["source"]})

    # which catalogue lines still have no photograph of their own
    with open(os.path.join(ROOT, "shop", "assets", "js", "data.js"), encoding="utf-8") as f:
        data = f.read()
    catalogue = json.loads(data.split("window.CATALOG = ", 1)[1].rstrip().rstrip(";"))
    missing = [p["slug"] for p in catalogue if p["slug"] not in products]
    aisle_of = {p["slug"]: slugify(p["c"]) for p in catalogue}

    js = ("/* Generated by tools/apply_photos.py from tools/photos.json.\n"
          "   Every URL here came back from the Unsplash API — none is hand-written. */\n"
          "window.PHOTOS = %s;\n\nwindow.AISLE_PHOTOS = %s;\n\nwindow.SCENE_PHOTOS = %s;\n\n"
          "window.PHOTO_AISLE_OF = %s;\n\nwindow.PHOTO_CREDITS = %s;\n"
          % (json.dumps(products, indent=1, ensure_ascii=False),
             json.dumps(aisles, indent=1, ensure_ascii=False),
             json.dumps(scenes, indent=1, ensure_ascii=False),
             json.dumps(aisle_of, indent=1, ensure_ascii=False),
             json.dumps(credits, indent=1, ensure_ascii=False)))

    out = os.path.join(ROOT, "shop", "assets", "js", "photos.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write(js)

    print("photos.js written")
    print("  products with their own photograph : %d of %d" % (len(products), len(catalogue)))
    print("  aisle photographs                  : %d" % len(aisles))
    print("  scene photographs                  : %d" % len(scenes))
    if missing:
        print("\n  still on an aisle photograph (%d):" % len(missing))
        for m in missing:
            print("    -", m)

if __name__ == "__main__":
    main()
