# -*- coding: utf-8 -*-
"""
Photo pipeline: manifest -> downloaded, cropped, self-hosted photographs.

Why a manifest: this build machine cannot reach any image host, so the photos
are chosen through the Unsplash API (which returns authoritative URLs — nothing
is guessed) and written into tools/photos.json. Fetching and cropping then runs
anywhere with a normal internet connection.

    python3 tools/photos.py fetch     # download + crop + write files
    python3 tools/photos.py apply     # point data.js at the local photos
    python3 tools/photos.py sheet     # contact sheet for eyeballing all of them
    python3 tools/photos.py status    # what is present, what is missing

Requires: pillow  (pip install pillow)

Every entry keeps its photographer and source URL. Unsplash does not require
attribution, but crediting the photographer is the decent thing to do and the
credits page is generated from the same manifest.
"""
import io, json, os, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MANIFEST = os.path.join(HERE, "photos.json")
OUT = os.path.join(ROOT, "shop", "assets", "img", "photos")
DATA = os.path.join(ROOT, "shop", "assets", "js", "data.js")

# target box per kind of image, and the crop that suits it
SIZES = {
    "product": (900, 675),    # 4:3, matches the product tile
    "aisle":   (1200, 480),   # 5:2 banner
    "scene":   (1600, 1100),  # hero and marketing art
}
UA = {"User-Agent": "RetailCore-photo-fetch/1.0 (+https://github.com)"}


def load():
    if not os.path.exists(MANIFEST):
        sys.exit("No manifest yet. tools/photos.json is written once the photos "
                 "have been chosen through the Unsplash API.")
    with open(MANIFEST, encoding="utf-8") as f:
        return json.load(f)


def crop_to(img, box):
    """Cover-crop from the centre so nothing is squashed."""
    from PIL import Image
    tw, th = box
    sw, sh = img.size
    scale = max(tw / sw, th / sh)
    nw, nh = int(round(sw * scale)), int(round(sh * scale))
    img = img.resize((nw, nh), Image.LANCZOS)
    left, top = (nw - tw) // 2, (nh - th) // 2
    return img.crop((left, top, left + tw, top + th))


def fetch():
    try:
        from PIL import Image
    except ImportError:
        sys.exit("Pillow is needed for cropping:  pip install pillow")

    man = load()
    os.makedirs(OUT, exist_ok=True)
    done = skipped = failed = 0

    for key, e in sorted(man["photos"].items()):
        dest = os.path.join(OUT, key + ".jpg")
        if os.path.exists(dest) and not os.environ.get("FORCE"):
            skipped += 1
            continue
        try:
            req = urllib.request.Request(e["download"], headers=UA)
            with urllib.request.urlopen(req, timeout=60) as r:
                raw = r.read()
            img = Image.open(io.BytesIO(raw)).convert("RGB")
            img = crop_to(img, SIZES[e.get("kind", "product")])
            img.save(dest, "JPEG", quality=82, optimize=True, progressive=True)
            done += 1
            print("  ok      %-28s %6.0f KB" % (key, os.path.getsize(dest) / 1024))
        except Exception as ex:                      # keep going; report at the end
            failed += 1
            print("  FAILED  %-28s %s" % (key, ex))

    print("\nfetched %d, already present %d, failed %d" % (done, skipped, failed))
    if failed:
        print("Re-run to retry only the failures — finished files are skipped.")
    return failed == 0


def apply():
    """Point the catalogue at local photographs, keeping a drawing as fallback."""
    man = load()
    with open(DATA, encoding="utf-8") as f:
        data = f.read()
    changed = 0
    for key, e in man["photos"].items():
        if e.get("kind") != "product":
            continue
        if not os.path.exists(os.path.join(OUT, key + ".jpg")):
            continue                                  # not fetched yet, leave it alone
        old = '"img": "assets/img/products/%s.svg"' % key
        new = '"img": "assets/img/photos/%s.jpg"' % key
        if old in data:
            data = data.replace(old, new)
            changed += 1
    with open(DATA, "w", encoding="utf-8") as f:
        f.write(data)
    print("pointed %d catalogue lines at photographs" % changed)
    write_credits(man)


def write_credits(man):
    rows = []
    for key, e in sorted(man["photos"].items()):
        if e.get("photographer"):
            rows.append({"key": key, "by": e["photographer"],
                         "profile": e.get("profile", ""), "source": e.get("source", "")})
    path = os.path.join(ROOT, "shop", "assets", "js", "credits.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/photos.py — photographer credits. */\n"
                "window.PHOTO_CREDITS = %s;\n" % json.dumps(rows, indent=1, ensure_ascii=False))
    print("wrote credits for %d photographs" % len(rows))


def sheet():
    """A single page showing every photograph next to the line it represents,
    so a mismatch is caught before the client ever sees it."""
    man = load()
    cells = []
    for key, e in sorted(man["photos"].items()):
        src = "../shop/assets/img/photos/%s.jpg" % key
        cells.append(
            '<figure><img src="%s" alt="" loading="lazy">'
            '<figcaption><b>%s</b><span>%s</span><span class="by">%s</span></figcaption></figure>'
            % (src, key, e.get("query", ""), e.get("photographer", "")))
    html = ("<!doctype html><meta charset=utf-8><title>Photo review</title>"
            "<style>body{margin:0;padding:24px;background:#111;color:#eee;"
            "font:14px/1.4 system-ui,sans-serif}"
            "h1{font-size:18px;margin:0 0 18px}"
            "div{display:grid;gap:14px;grid-template-columns:repeat(auto-fill,minmax(230px,1fr))}"
            "figure{margin:0;background:#1c1c1c;border-radius:6px;overflow:hidden}"
            "img{width:100%%;aspect-ratio:4/3;object-fit:cover;display:block;background:#333}"
            "figcaption{padding:9px 11px;display:grid;gap:3px}"
            "b{font-size:13px}span{font-size:11px;color:#9aa}"
            ".by{color:#667}</style>"
            "<h1>%d photographs — check each one matches its line</h1><div>%s</div>"
            % (len(cells), "".join(cells)))
    path = os.path.join(ROOT, "dist", "photo-review.html")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    print("wrote", path)


def status():
    man = load() if os.path.exists(MANIFEST) else {"photos": {}}
    have = set(f[:-4] for f in os.listdir(OUT)) if os.path.isdir(OUT) else set()
    want = set(man["photos"])
    print("manifest entries : %d" % len(want))
    print("downloaded       : %d" % len(want & have))
    missing = sorted(want - have)
    if missing:
        print("missing          : %d" % len(missing))
        for m in missing[:12]:
            print("   -", m)
        if len(missing) > 12:
            print("   … and %d more" % (len(missing) - 12))


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "status"
    {"fetch": fetch, "apply": apply, "sheet": sheet, "status": status}.get(cmd, status)()
